export const GET_CHANNELS_REQUEST='GET_CHANNELS_REQUEST'
export const GET_CHANNELS_FAILURE='GET_CHANNELS_FAILURE'
export const GET_CHANNELS_SUCCESS='GET_CHANNELS_SUCCESS'


export const ADD_CHANNELS_REQUEST='ADD_CHANNELS_REQUEST'
export const ADD_CHANNELS_FAILURE='ADD_CHANNELS_FAILURE'
export const ADD_CHANNELS_SUCCESS='ADD_CHANNELS_SUCCESS'


export const DELETE_CHANNELS_REQUEST='DELETE_CHANNELS_REQUEST'
export const DELETE_CHANNELS_FAILURE='DELETE_CHANNELS_FAILURE'
export const DELETE_CHANNELS_SUCCESS = 'DELETE_CHANNELS_SUCCESS'


export const GET_FACEBOOKDATA_REQUEST='GET_FACEBOOKDATA_REQUEST'
export const GET_FACEBOOKDATA_FAILURE='GET_FACEBOOKDATA_FAILURE'
export const GET_FACEBOOKDATA_SUCCESS='GET_FACEBOOKDATA_SUCCESS'


export const GET_INSTAGRAMDATA_REQUEST='GET_INSTAGRAMDATA_REQUEST'
export const GET_INSTAGRAMDATA_FAILURE='GET_INSTAGRAMDATA_FAILURE'
export const GET_INSTAGRAMDATA_SUCCESS='GET_INSTAGRAMDATA_SUCCESS'



