export const engagementdata = [
    {
        id:1,
        imgurl:"https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Roaring lion",
        days:"2 weeks ago",
        likes:40,
        commentsno:0,
        comments:[],
    },
    {
        id:2,
        imgurl:"https://images.pexels.com/photos/47547/squirrel-animal-cute-rodents-47547.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Eating Squirrel",
        days:"1 weeks ago",
        likes:44,
        commentsno:0,
        comments:[],
    },
    {
        id:3,
        imgurl:"https://images.pexels.com/photos/1661179/pexels-photo-1661179.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Parrot",
        days:"3 weeks ago",
        likes:455,
        commentsno:0,
        comments:[],
    },
    {
        id:4,
        imgurl:"https://images.pexels.com/photos/792381/pexels-photo-792381.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Tiger in black",
        days:"8 weeks ago",
        likes:4,
        commentsno:0,
        comments:[],
    },    
    {
        id:5,
        imgurl:"https://images.pexels.com/photos/34231/antler-antler-carrier-fallow-deer-hirsch.jpg?auto=compress&cs=tinysrgb&w=600",
        caption:"12singha",
        days:"8 weeks ago",
        likes:4,
        commentsno:0,
        comments:[],
    },
    {
        id:6,
        imgurl:"https://images.pexels.com/photos/67552/giraffe-tall-mammal-africa-67552.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Giraffe",
        days:"8 weeks ago",
        likes:45,
        commentsno:0,
        comments:[],
    },    
    {
        id:7,
        imgurl:"https://images.pexels.com/photos/62289/yemen-chameleon-chamaeleo-calyptratus-chameleon-reptile-62289.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Green Chameleon",
        days:"9 weeks ago",
        likes:488,
        commentsno:0,
        comments:[],
    },
    {
        id:8,
        imgurl:"https://images.pexels.com/photos/325045/pexels-photo-325045.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Unique Fish",
        days:"9 weeks ago",
        likes:477,
        commentsno:0,
        comments:[],
    },    
    {
        id:9,
        imgurl:"https://images.pexels.com/photos/162140/duckling-birds-yellow-fluffy-162140.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"duckling-birds-yellow-fluffy",
        days:"10 weeks ago",
        likes:554,
        commentsno:0,
        comments:[],
    },
    {
        id:10,
        imgurl:"https://images.pexels.com/photos/39317/chihuahua-dog-puppy-cute-39317.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"chihuahua-dog-puppy-cute",
        days:"10 weeks ago",
        likes:774,
        commentsno:0,
        comments:[],
    },    
    {
        id:11,
        imgurl:"https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Twin puppy",
        days:"10 weeks ago",
        likes:454,
        commentsno:0,
        comments:[],
    },
    {
        id:12,
        imgurl:"https://images.pexels.com/photos/219906/pexels-photo-219906.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Black and white filtered Deer",
        days:"11 weeks ago",
        likes:884,
        commentsno:0,
        comments:[],
    },    
    {
        id:13,
        imgurl:"https://images.pexels.com/photos/45911/peacock-plumage-bird-peafowl-45911.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"peacock-plumage-bird-peafowl",
        days:"11 weeks ago",
        likes:334,
        commentsno:0,
        comments:[],
    },
    {
        id:14,
        imgurl:"https://images.pexels.com/photos/97533/pexels-photo-97533.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Parrot with red cherries",
        days:"12 weeks ago",
        likes:224,
        commentsno:0,
        comments:[],
    },    
    {
        id:15,
        imgurl:"https://images.pexels.com/photos/33787/chimpanzee-sitting-sad-mammal.jpg?auto=compress&cs=tinysrgb&w=600",
        caption:"chimpanzee-sitting-sad-mammal",
        days:"12 weeks ago",
        likes:884,
        commentsno:0,
        comments:[],
    },
    {
        id:16,
        imgurl:"https://images.pexels.com/photos/17811/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600",
        caption:"Long beak bird",
        days:"13 weeks ago",
        likes:664,
        commentsno:0,
        comments:[],
    },    
    {
        id:17,
        imgurl:"https://images.pexels.com/photos/635499/pexels-photo-635499.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Brown Horse",
        days:"14 weeks ago",
        likes:564,
        commentsno:0,
        comments:[],
    },
    {
        id:18,
        imgurl:"https://images.pexels.com/photos/162203/panthera-tigris-altaica-tiger-siberian-amurtiger-162203.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"panthera-tigris-altaica-tiger-siberian-amurtiger",
        days:"14 weeks ago",
        likes:984,
        commentsno:0,
        comments:[],
    },    
    {
        id:19,
        imgurl:"https://images.pexels.com/photos/326012/pexels-photo-326012.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Innocent rabbit",
        days:"15 weeks ago",
        likes:654,
        commentsno:0,
        comments:[],
    },
    {
        id:20,
        imgurl:"https://images.pexels.com/photos/847393/pexels-photo-847393.jpeg?auto=compress&cs=tinysrgb&w=600",
        caption:"Underwater turtle",
        days:"15 weeks ago",
        likes:684,
        commentsno:0,
        comments:[],
    },    
    
]